# Generated by Django 5.1.7 on 2025-04-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_virtualpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
