# Generated by Django 5.1.7 on 2025-04-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_club_membership_fee_event_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
